# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ee63c8f17fc522b6409c45e5631eeb904e7cdac871189a650e85454d4593badf077000a7b39ad39d1d4495b624b18a82cee05ed7c3f7d75235dfa82927307ab5

test:
  secret_key_base: ba895ee917c78197897ffc053aadd10da98f62a0ae988c0259977f7ea80f000c8c16f9d097176902f005b6bc6dac25ecd1f772118709028bbcbcef166098ffbf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
